In [9]:
import pandas as pd
import numpy as np
import glob
import os

In [10]:
path = 'resources/weather'

In [11]:
#Get a list of all csv file paths in the folder
all_files = glob.glob(os.path.join(path, "*.csv"))

#Create a list of dataframes
df_list = []

for filename in all_files:
    df = pd.read_csv(filename)
    df_list.append(df)

#Find the intersection of columns across all DataFrames, preserving order from the first DataFrame
if df_list:
    #Get columns from the first DataFrame as a reference for order
    first_df_cols = df_list[0].columns.tolist()
    all_df_cols_sets = [set(df.columns) for df in df_list]
    common_cols_set = set.intersection(*all_df_cols_sets)
    common_cols = [col for col in first_df_cols if col in common_cols_set]
else:
    common_cols = []

#Select only the common columns from each DataFrame, in the preserved order
df_list_common = [df[common_cols] for df in df_list]

#Stack them vertically
weather_df = pd.concat(df_list_common, axis=0, ignore_index=True)

#Check the results
print(f"Combined {len(all_files)} files.")
print(f"Number of common columns kept: {len(common_cols)}")
weather_df.head()

Combined 13 files.
Number of common columns kept: 19

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TAVG,WT01,WT02,WT03,WT04,WT05,WT06,WT07,WT08,WT09,WT10,WT11
0,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-22,NaN,0.41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-23,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-25,NaN,0.21,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-26,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-27,NaN,0.00,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
#Identify all columns that start with "WT" (weather type binaries)
wt_cols = [col for col in weather_df.columns if col.startswith('WT')]

#Fill the missing (NaN) values with 0
weather_df[wt_cols] = weather_df[wt_cols].fillna(0).astype(int)

#Verify the change
print(f"Updated {len(wt_cols)} columns: {wt_cols}")
weather_df[wt_cols].head()

Updated 11 columns: ['WT01', 'WT02', 'WT03', 'WT04', 'WT05', 'WT06', 'WT07', 'WT08', 'WT09', 'WT10', 'WT11']

   WT01  WT02  WT03  WT04  WT05  WT06  WT07  WT08  WT09  WT10  WT11
0     0     0     0     0     0     0     0     0     0     0     0
1     0     0     0     0     0     0     0     0     0     0     0
2     0     0     0     0     0     0     0     0     0     0     0
3     0     0     0     0     0     0     0     0     0     0     0
4     0     0     0     0     0     0     0     0     0     0     0

In [13]:
#Rename weather types to reflect their meanings
weather_map = {
    'WT01': 'Fog_Ice_Fog',
    'WT02': 'Heavy_Fog',
    'WT03': 'Thunder',
    'WT04': 'Ice_Pellets_Sleet',
    'WT05': 'Hail',
    'WT06': 'Glaze_Rime',
    'WT07': 'Dust_Ash_Sand',
    'WT08': 'Smoke_Haze',
    'WT09': 'Blowing_Snow',
    'WT10': 'Tornado_Funnel_Cloud',
    'WT11': 'High_Winds',
    'WT12': 'Blowing_Spray',
    'WT13': 'Mist',
    'WT14': 'Drizzle',
    'WT15': 'Freezing_Drizzle',
    'WT16': 'Rain',
    'WT17': 'Freezing_Rain',
    'WT18': 'Snow',
    'WT19': 'Unknown_Precip',
    'WT21': 'Ground_Fog',
    'WT22': 'Ice_Fog'
}

#Apply the rename
weather_df = weather_df.rename(columns=weather_map)
weather_df.head()

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TAVG,Fog_Ice_Fog,Heavy_Fog,Thunder,Ice_Pellets_Sleet,Hail,Glaze_Rime,Dust_Ash_Sand,Smoke_Haze,Blowing_Snow,Tornado_Funnel_Cloud,High_Winds
0,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-22,NaN,0.41,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
1,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-23,NaN,0.00,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
2,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-25,NaN,0.21,NaN,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
3,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-26,NaN,0.00,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0
4,US1INLK0035,"ST. JOHN 1.9 ENE, IN US",2014-04-27,NaN,0.00,0.0,NaN,NaN,0,0,0,0,0,0,0,0,0,0,0

In [14]:
#Convert data types
weather_df['DATE'] = pd.to_datetime(weather_df['DATE'])

In [15]:
#Aggregate so there is only one row per date, preferring O'Hare as the station whenever available (because it's most consistently available in the dataset)
weather_df['preference'] = np.where(weather_df['NAME'] == 'CHICAGO OHARE INTERNATIONAL AIRPORT, IL US', 0, 1)
weather = weather_df.sort_values(by=['DATE', 'preference']).drop_duplicates(subset=['DATE'], keep='first').drop(columns=['preference'])
display(weather)

,STATION,NAME,DATE,AWND,PRCP,SNOW,SNWD,TAVG,Fog_Ice_Fog,Heavy_Fog,Thunder,Ice_Pellets_Sleet,Hail,Glaze_Rime,Dust_Ash_Sand,Smoke_Haze,Blowing_Snow,Tornado_Funnel_Cloud,High_Winds
270028,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2000-01-01,7.38,0.00,0.0,0.0,42.0,0,0,0,0,0,0,0,0,0,0,0
270029,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2000-01-02,13.87,0.01,0.0,0.0,48.0,1,0,0,0,0,0,0,0,0,0,0
270030,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2000-01-03,12.75,0.25,0.4,0.0,35.0,1,0,0,0,0,0,0,0,0,0,0
270031,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2000-01-04,13.42,0.00,0.0,0.0,28.0,1,0,0,0,0,0,0,0,0,0,0
270032,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2000-01-05,11.18,0.00,0.0,0.0,20.0,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
420724,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2026-01-28,9.62,0.00,0.0,2.0,NaN,0,0,0,0,0,0,0,0,0,0,0
420725,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2026-01-29,6.49,0.00,0.0,2.0,NaN,0,0,0,0,0,0,0,0,0,0,0
420726,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2026-01-30,10.29,0.10,2.6,2.0,NaN,0,0,0,0,0,0,0,0,0,0,0
420727,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2026-01-31,12.97,0.00,0.0,4.0,NaN,0,0,0,0,0,0,0,0,0,0,0
420728,USW00094846,"CHICAGO OHARE INTERNATIONAL AIRPORT, IL US",2026-02-01,8.50,0.00,0.0,3.0,NaN,0,0,0,0,0,0,0,0,0,0,0

In [17]:
output_path = ('resources')
file_name = 'weather_data'

#Save as .pkl
weather.to_pickle(os.path.join(output_path, f'{file_name}.pkl'))
print(f"DataFrame saved as {file_name}.pkl in {output_path}")

#Save as .csv
weather.to_csv(os.path.join(output_path, f'{file_name}.csv'), index=False)
print(f"DataFrame saved as {file_name}.csv in {output_path}")

DataFrame saved as weather_data.pkl in resources
DataFrame saved as weather_data.csv in resources